final List<Map<String, dynamic>> produk = [
  {
    'id': 1,
    'name': 'Nasi Gudeg Jogja',
    'description': 'Gudeg khas Yogyakarta dengan ayam dan telur',
    'price': 25000,
    'image': '🍛',
    'rating': 4.8,
    'sold': 120,
    'category': 'Makanan Utama',
    'restaurant': 'Warung Bu Sari',
  },
  {
    'id': 2,
    'name': 'Sate Ayam Madura',
    'description': 'Sate ayam dengan bumbu kacang khas Madura',
    'price': 20000,
    'image': '🍢',
    'rating': 4.7,
    'sold': 95,
    'category': 'Makanan Utama',
    'restaurant': 'Sate Pak Harto',
  },
  {
    'id': 3,
    'name': 'Es Cendol Durian',
    'description': 'Minuman segar dengan cendol dan durian',
    'price': 15000,
    'image': '🥤',
    'rating': 4.6,
    'sold': 78,
    'category': 'Minuman',
    'restaurant': 'Es Kelapa Muda',
  },
  {
    'id': 4,
    'name': 'Rendang Padang',
    'description': 'Rendang daging sapi khas Padang yang gurih',
    'price': 35000,
    'image': '🍖',
    'rating': 4.9,
    'sold': 156,
    'category': 'Makanan Utama',
    'restaurant': 'Rumah Makan Minang',
  },
  {
    'id': 5,
    'name': 'Bakso Malang',
    'description': 'Bakso dengan berbagai isian khas Malang',
    'price': 18000,
    'image': '🍜',
    'rating': 4.5,
    'sold': 89,
    'category': 'Makanan Utama',
    'restaurant': 'Bakso Pak Kumis',
  },
  {
    'id': 6,
    'name': 'Martabak Manis',
    'description': 'Martabak manis dengan topping cokelat keju',
    'price': 22000,
    'image': '🥞',
    'rating': 4.4,
    'sold': 67,
    'category': 'Cemilan',
    'restaurant': 'Martabak 65A',
  },
  {
    'id': 7,
    'name': 'Gado-gado Jakarta',
    'description': 'Sayuran segar dengan bumbu kacang khas Jakarta',
    'price': 12000,
    'image': '🥗',
    'rating': 4.3,
    'sold': 45,
    'category': 'Makanan Sehat',
    'restaurant': 'Gado-gado Bu Tini',
  },
  {
    'id': 8,
    'name': 'Es Teh Manis',
    'description': 'Minuman teh manis segar',
    'price': 5000,
    'image': '🧊',
    'rating': 4.2,
    'sold': 234,
    'category': 'Minuman',
    'restaurant': 'Warung Teh Asli',
  },
];

final List<String> categories = [
  'Semua',
  'Makanan Utama',
  'Cemilan',
  'Minuman',
  'Makanan Sehat',
];
