// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMSrlpYsUQphQLmE_95ulDSu25NFbl1O8',
    appId: '1:875861831208:web:a0474bece243f8ff128f1d',
    messagingSenderId: '875861831208',
    projectId: 'smartkulinner',
    authDomain: 'smartkulinner.firebaseapp.com',
    storageBucket: 'smartkulinner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOyFVQIitPnR927Pj7aIJvuzWSZ7RiXus',
    appId: '1:875861831208:android:efcdbe9ac9e319cc128f1d',
    messagingSenderId: '875861831208',
    projectId: 'smartkulinner',
    storageBucket: 'smartkulinner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5YOum93exxFNUCEgor4ri0WFSoOsz13Q',
    appId: '1:875861831208:ios:09ddaae717466b6d128f1d',
    messagingSenderId: '875861831208',
    projectId: 'smartkulinner',
    storageBucket: 'smartkulinner.firebasestorage.app',
    iosBundleId: 'com.example.smart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMSrlpYsUQphQLmE_95ulDSu25NFbl1O8',
    appId: '1:875861831208:web:b23cf2e23efdaaed128f1d',
    messagingSenderId: '875861831208',
    projectId: 'smartkulinner',
    authDomain: 'smartkulinner.firebaseapp.com',
    storageBucket: 'smartkulinner.firebasestorage.app',
  );
}
